using System.Text;
using MonadicStudio.Api.Models;

namespace MonadicStudio.Api.Services;

public sealed class CodeGeneratorService
{
    private readonly RoslynCodeFormatterService _formatter;
    private readonly SolutionLinkService _solutionLink;

    public CodeGeneratorService(RoslynCodeFormatterService formatter, SolutionLinkService solutionLink)
    {
        _formatter = formatter;
        _solutionLink = solutionLink;
    }

    public GenerateResponse Generate(GenerateRequest request)
    {
        if (request.Nodes.Count == 0)
            return new GenerateResponse("// Pipeline vuota — aggiungi nodi al canvas.", [], true);

        var rawCode = BuildRawCode(request);
        var (formatted, diagnostics, isValid) = _formatter.FormatAndValidate(rawCode);
        return new GenerateResponse(formatted, diagnostics, isValid);
    }

    public string BuildRawCode(GenerateRequest request)
    {
        var isFunctional = request.ParadigmStyle.Equals("Functional ROP", StringComparison.OrdinalIgnoreCase);
        var sb = new StringBuilder();

        AppendHeader(sb, request);

        foreach (var node in request.Nodes.Where(n => n.Type == "metaCreation"))
            AppendMetaExtensionStub(sb, node);

        sb.AppendLine();
        AppendPipeline(sb, request, isFunctional);

        return sb.ToString();
    }

    private void AppendHeader(StringBuilder sb, GenerateRequest request)
    {
        sb.AppendLine("// Generated by MonadicStudio — MonadicSharp ROP");
        sb.AppendLine($"// C# Target: {request.CSharpVersion}");
        sb.AppendLine($"// Paradigm: {request.ParadigmStyle}");
        sb.AppendLine("using MonadicSharp;");
        sb.AppendLine();

        var ns = _solutionLink.GetSettings().RootNamespace;
        if (!string.IsNullOrWhiteSpace(ns))
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }
    }

    private static void AppendMetaExtensionStub(StringBuilder sb, PipelineNode node)
    {
        var prompt = string.IsNullOrWhiteSpace(node.Prompt) ? "UnnamedMapping" : node.Prompt.Trim();
        var methodName = ToPascalCase(prompt);
        var inputType = node.InputType ?? "object";
        var outputType = NormalizeMonadicType(node.OutputType ?? "object");

        sb.AppendLine($"public static class {methodName}Extensions");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Stub generato dal prompt: \"{prompt}\"</summary>");
        sb.AppendLine($"    public static {outputType} {methodName}(this {inputType} source)");
        sb.AppendLine("    {");
        sb.AppendLine($"        // TODO: Implementare mapping — \"{prompt}\"");
        sb.AppendLine($"        return {outputType}.Failure(Error.Create(\"{methodName} not implemented\"));");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendPipeline(StringBuilder sb, GenerateRequest request, bool isFunctional)
    {
        var nodes = request.Nodes;
        var firstInput = nodes[0].InputType ?? "object";
        var lastResult = NormalizeMonadicType(nodes[^1].OutputType ?? "Result<object>");

        sb.AppendLine("public static class GeneratedPipeline");
        sb.AppendLine("{");
        sb.AppendLine($"    public static {lastResult} Execute({firstInput} input)");
        sb.AppendLine("    {");

        if (isFunctional)
            AppendFunctionalPipeline(sb, nodes, lastResult);
        else
            AppendImperativePipeline(sb, nodes, lastResult);

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void AppendFunctionalPipeline(StringBuilder sb, IReadOnlyList<PipelineNode> nodes, string lastResult)
    {
        var chain = new StringBuilder();
        chain.Append("        return Result.Success(input)");

        foreach (var node in nodes)
        {
            chain.AppendLine();
            chain.Append("            ");

            if (node.Type == "metaCreation")
            {
                var methodName = ToPascalCase(node.Prompt ?? "UnnamedMapping");
                chain.Append($".Bind(x => x.{methodName}())");
            }
            else
            {
                var reference = FormatMethodReference(node);
                chain.Append($".Bind({reference})");
            }
        }

        chain.Append(";");
        sb.AppendLine(chain.ToString());
    }

    private static void AppendImperativePipeline(StringBuilder sb, IReadOnlyList<PipelineNode> nodes, string lastResult)
    {
        sb.AppendLine("        var current = input;");
        sb.AppendLine();

        for (var i = 0; i < nodes.Count; i++)
        {
            var node = nodes[i];
            var varName = $"step{i + 1}";

            if (node.Type == "metaCreation")
            {
                var methodName = ToPascalCase(node.Prompt ?? "UnnamedMapping");
                sb.AppendLine($"        var {varName} = current.{methodName}();");
            }
            else
            {
                sb.AppendLine($"        var {varName} = {FormatMethodReference(node)}(current);");
            }

            sb.AppendLine($"        if ({varName}.IsFailure) return {lastResult}.Failure({varName}.Error);");
            sb.AppendLine($"        current = {varName}.Value;");
            sb.AppendLine();
        }

        sb.AppendLine($"        return Result.Success(current);");
    }

    private static string FormatMethodReference(PipelineNode node)
    {
        if (string.IsNullOrWhiteSpace(node.ClassName))
            return node.MethodName ?? "UnknownMethod";

        return $"{node.ClassName}.{node.MethodName}";
    }

    private static string NormalizeMonadicType(string typeName)
    {
        if (string.IsNullOrWhiteSpace(typeName))
            return "Result<object>";

        if (typeName.StartsWith("Result<", StringComparison.Ordinal))
        {
            var inner = ExtractGenericInner(typeName);
            if (inner is not null && inner.Contains("Error", StringComparison.Ordinal))
                return $"Result<{inner.Split(',')[0].Trim()}>";
            return typeName;
        }

        return $"Result<{typeName.Trim()}>";
    }

    private static string ToPascalCase(string value)
    {
        var words = value
            .Split([' ', '_', '-'], StringSplitOptions.RemoveEmptyEntries)
            .Select(w => char.ToUpperInvariant(w[0]) + w[1..]);

        var result = string.Concat(words);
        return string.IsNullOrEmpty(result) ? "UnnamedMapping" : result;
    }

    private static string? ExtractGenericInner(string? typeName)
    {
        if (string.IsNullOrWhiteSpace(typeName)) return null;

        var start = typeName.IndexOf('<');
        var end = typeName.LastIndexOf('>');
        if (start < 0 || end <= start) return null;

        return typeName[(start + 1)..end];
    }
}
